apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartpark-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartpark-redis
  template:
    metadata:
      labels:
        app: smartpark-redis
    spec:
      containers:
        - name: redis
          image: redis:8.2.9-alpine
          args:
            - redis-server
            - --maxmemory
            - 128mb
            - --maxmemory-policy
            - allkeys-lru
            - --save
            - ""
            - --appendonly
            - "no"
          ports:
            - name: redis
              containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: redis
          livenessProbe:
            tcpSocket:
              port: redis
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: smartpark-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
  type: ClusterIP